version: 2

jobs:
  lint:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip install black flake8
      - run: black --check .
      - run: flake8 .
  build:
    working_directory: ~/work
    docker:
      - image: circleci/python:3
    steps:
    steps:
      - run: sudo apt update
      - run: sudo apt install -y python3-dolfin curl
      - run: pip3 install -U pytest pytest-cov
      - checkout
      - run: pip3 install .
      - run: pip3 install -r test_requirements.txt
      #
      - run: curl https://people.sc.fsu.edu/~jburkardt/data/mm/gre_343_343_crg.mm > test/gre_343_343_crg.mm
      # The tests
      - run:
          command: pytest --cov betterspy
          working_directory: test/
          env:
            MPLBACKEND: Agg
      # submit to codecov
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build
